### ISSUE TITLE
ENH: Parse text-based MyST Markdown notebooks

### ISSUE THREAD

**Issue by mmcky** [executablebooks/jupyterlab-mystjs#10]
### Context

One workflow that works well for us is to edit `myst:md` files directly rather than use `ipynb`.  The primary benefit to this are easy git version control for repositories. 

### Proposal

`jupytext` allows for opening `md` files directly via a context manager in `jupyter` however `jupyterlab-mystjs` doesn't seem to render the `myst` defaulting back to the default jupyter rendering.

It would be nice to render a notebook that is actually an `md` file on the disk

### Tasks and updates

This might be as simple as recognising multiple file types? `.md` and `.ipynb` to switch on `markdown` cell rendering.

**Comment by choldgraf** [comment]
I updated the issue title so that is more "outcome focused" rather than "implementation focused" around Jupytext. I think ultimately what we'd like is for MyST Markdown notebooks to be parse-able by MyST-JS in JupyterLab, not that jupytext specifically be used to do the parsing (even if Jupytext is ultimately what we decide to use). Hope that is OK @mmcky !

**Comment by rowanc1** [comment]
Testing with jupytext locally, it seems to work if you open with jupytext notebook renderer __first__ then you can work with mystjs once it is a notebook. Jupytext takes care of the saving it seems, and doesn't modify the cells.

I have no idea what magic is happening to make the jupytext happen, but we probably just need to implement the menu item to do the first trigger? @agoose77 might have some better pointers to things?!

![jupytext](https://user-images.githubusercontent.com/913249/215909291-a752040f-4d48-4dad-9932-ca9bc68e09b6.gif)

**Comment by agoose77** [comment]
Huh, I never actually looked at how JupyText worked under the hood. It looks like it provides its own contents-manager implementation, which allows the frontend to request a Markdown file as a JSON notebook.

JupyText then create their own `NotebookWidgetFactory` that extends the existing factory for the additional file types: https://github.com/mwouts/jupytext/blob/aae7c64e12033bfe73e72536f068932f3d6ac06f/packages/labextension/src/index.ts#L449-L467

So, it's not the MD rendering that's being used; we're replacing the Notebook renderer, but JupyText is finding the old one (as we never expose our new one to other extensions).

I *think* what we want to do is to provide the `INotebookPanel.ContentFactory` token, currently provided by JupyterLab:
https://github.com/jupyterlab/jupyterlab/blob/2e8677624ed7301d47de703570a14ce3bb8036cf/packages/notebook-extension/src/index.ts#L343-L352 

This would expose our content factory 
https://github.com/executablebooks/jupyterlab-mystjs/blob/3d9016fc131637e26a712cc7d2737fa4f78cc66a/src/index.ts#L67

to the other extensions that build the notebook experience, e.g.
https://github.com/jupyterlab/jupyterlab/blob/2e8677624ed7301d47de703570a14ce3bb8036cf/packages/notebook-extension/src/index.ts#L669-L684

which produces the `INotebookWidgetFactory` that JupyText consumes:

https://github.com/mwouts/jupytext/blob/aae7c64e12033bfe73e72536f068932f3d6ac06f/packages/labextension/src/index.ts#L186

There's precedent for this; JupyterLab is designed to be modular in this way. To provide `INotebookPanel.ContentFactory` we would need to disable the built-in plugin, I think.

**Comment by rowanc1** [comment]
Thanks for all the links @agoose77, always so helpful. :)

The first one I think does the trick for me, in the `NotebookWidgetFactory` I added `markdown` and `myst` similar to jupytext:
![image](https://user-images.githubusercontent.com/913249/215929508-551df0d5-bbb3-4d2b-9228-e14c7e7af00a.png)

This allows you to open the markdown file directly as a notebook, when you save, that puts the `ipynb` with the outputs next to the markdown file and keeps them in sync.
![image](https://user-images.githubusercontent.com/913249/215929435-aaff1056-921e-4982-850e-ed94606264af.png)

I think that was @mmcky's original request!? I will put together the tiny PR, which is an improvement, but I might be missing something larger in the workflow.
