### ISSUE TITLE
MyST Notebook should appear as an option(s) in the Launcher

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/jupyterlab-mystjs#2]
### Context

Currently the launcher only allows normal notebooks to be launched. So when creating a new notebook, it will be opened with the normal renderer. A user has to close the notebook and reopen it for it to be rendered with myst

![image](https://user-images.githubusercontent.com/1473646/212306079-d526aed3-ef0c-45d1-b54f-51b043f9ebcc.png)

### Proposal

Add a MyST Notebook section to the launcher!

**Comment by agoose77** [comment]
Can this be closed, now that we support JupyText?

**Comment by rowanc1** [comment]
Yeah, and that it is now the default renderer, I think this is no longer necessary.
