### ISSUE TITLE
HTML comments shouldn't render in mardkown cells

### ISSUE THREAD

**Issue by fperez** [executablebooks/jupyterlab-mystjs#34]
### Describe the bug

**context**
When I type an html comment in markdown. Consider a cell with this content:

```
A **repository**: a group of *linked* commits

<!-- offline: 
![](files/images/threecommits.png)

<img src="https://raw.github.com/fperez/reprosw/master/fig/threecommits.png" >
-->
```

**expectation**
I expected it not to render the comment, and show only this:

![image](https://user-images.githubusercontent.com/57394/217396289-ba281423-c040-4f0e-a24b-50647c681761.png)

**bug**
But instead it renders as:

![image](https://user-images.githubusercontent.com/57394/217396503-0b7ee935-586e-41f0-9e47-eee3bc0a8966.png)

**problem**
This is a problem b/c we often use comments to temporarily elide parts of a markdown cell or provide extra info not meant to be rendered. 

### Reproduce the bug

See above - happens with 0.1.3

### Edit

Fixed accidentally incorrect screenie.

**Comment by mcauthorn** [comment]
In the event it helps: I've run into a version of the same bug. I had a markdown cell with the following HTML inside of it to render a resized image, which worked before installation of jupyterlab-mystjs:
```html
<div>
    <img src="attachment:61feef8d-4746-446a-bfbd-191d469fbcdc.png" width="250"/>
</div>
```

After installation, the raw HTML is rendering instead of the (expected) image:
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/2439265/217439034-5e09dbd7-1635-439d-9008-edfe7a857819.png">

**Comment by rowanc1** [comment]
Thanks @mcauthorn and @fperez for the feedback, we will aim to get this fixed up soon, I think we somehow need to enable the html parts:

@fwkoch I have put together a sandbox example here [html-comments/images](https://myst-tools.org/sandbox?tab=ast&myst=PAAhAC0ALQAgAHAAbABlAGEAcwBlACAAbQBhAGsAZQAgAHQAaABlACAAaAB0AG0AbAAgAGMAbwBtAG0AZQBuAHQAcwAsACAAdwBlAGwAbAAgAGMAbwBtAG0AZQBuAHQAcwAhACAAaQBuAGMAbAB1AGQAaQBuAGcAIAB0AGgAaQBzACAAbwBuAGUAIQAgAC0ALQA%2BACAAPABwAD4AbgBvAHQAIABhACAAYwBvAG0AbQBlAG4AdAAhADwALwBwAD4ACgAKAFQAaABpAHMAIABzAGgAbwB1AGwAZAAgAGIAZQAgAHAAYQByAHMAZQBkACAAcAByAG8AcABlAHIAbAB5ACAAaQBuAHQAbwAgAGEAbgAgAGkAbQBhAGcAZQAhAAoACgA8AGQAaQB2AD4ACgAgACAAIAAgADwAaQBtAGcAIABzAHIAYwA9ACIAYQB0AHQAYQBjAGgAbQBlAG4AdAA6ADYAMQBmAGUAZQBmADgAZAAtADQANwA0ADYALQA0ADQANgBhAC0AYgBmAGIAZAAtADEAOQAxAGQANAA2ADkAZgBiAGMAZABjAC4AcABuAGcAIgAgAHcAaQBkAHQAaAA9ACIAMgA1ADAAIgAvAD4ACgA8AC8AZABpAHYAPgA%3D) it does looks like they do get parsed to html, but I think we aren't taking them the rest of the way?

**Comment by rowanc1** [comment]
Hi @fperez and @mcauthorn -- there is a new version `v0.1.4` that provides better support for HTML parsing. It does catch the comments, and those are now no longer rendered (thank you @fwkoch!).

There is also a new feature that you can partially disable the full-renderer, and opt instead to open a MyST and a traditional version of the same notebook through the UI. This will require you to explicitly disable the "plugin" part, this will enable the other renderer -- there is more info in the readme!

The other HTML issues I am going to track in executablebooks/jupyterlab-myst#64 (e.g. @mcauthorn the width isn't preserved).
