### ISSUE TITLE
Initial H1 heading gets duplicated

### ISSUE THREAD

**Issue by fperez** [executablebooks/jupyterlab-mystjs#7]
### Describe the bug

**context**
If the first cell has an H1 heading, it gets doubly-rendered (the duplicate also shows up in the outline view):

![image](https://user-images.githubusercontent.com/57394/213330114-18a02843-26d7-4aa7-b56c-d1808ea77de0.png)

(this screenshot shows the same notebook opened on the left with the default renderer and on the right with this one).

### Reproduce the bug

Make the first cell have a `# H1 heading`.

**Comment by rowanc1** [comment]
Yes, I noticed this as well. Will take a look later this week.

We are parsing frontmatter and not pulling the header out of the document when just a title is found!

**Comment by rowanc1** [comment]
This has been released in `jupyterlab-mystjs@0.1.2`!!
