### ISSUE TITLE
Images and links need to be patched by Jupyter

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/jupyterlab-mystjs#8]
Currently the images to local paths are broken, these need to be properly patched by Jupyter. This is also true for links. We will have to go into the internals as we are taking over the rendering of the markdown cells entirely.

Some pointers from @agoose77:
> `jupyterlab-markup` integrates into JupyterLab's renderermime by exposing a markdown renderer, so JupyterLab takes the generated HTML and post-processes it. If you want to avoid generating HTML fragments and doing that, you can access the same interfaces that  JupyterLab's using

- [renderers](https://github.com/fcollonval/jupyterlab/blob/782ab8dbeaca46ae94998ae7ec04453e88b1fffb/packages/rendermime/src/renderers.ts#L21)

The URLs are patched here: 
 - [url patching](https://github.com/fcollonval/jupyterlab/blob/782ab8dbeaca46ae94998ae7ec04453e88b1fffb/packages/rendermime/src/renderers.ts#L88)

This private function uses these:
- [private function](https://github.com/fcollonval/jupyterlab/blob/782ab8dbeaca46ae94998ae7ec04453e88b1fffb/packages/rendermime/src/renderers.ts#L798-L799)

**Comment by rowanc1** [comment]
@fperez the images should be fixed in `jupyterlab-mystjs@0.1.2`. Links still outstanding, but progress!

**Comment by fperez** [comment]
Very cool, huge thanks @rowanc1!! I also see that the double-title problem is gone, much appreciated :)

When you fix links, I'd suggest rendering them similarly to the default in pre-existing JLab (blue, no underline), perhaps?

I'm thinking that for the "classic" markup where there's overlap with existing practice, it would help adoption in the community if things continue to work similarly. Here's a comparison (that shows the duplicate titles are now fixed):

![image](https://user-images.githubusercontent.com/57394/215908578-b1303446-0317-40ab-ba5a-1661cc3c09c1.png)

**Comment by rowanc1** [comment]
Yep - @fwkoch fixed up the double title in #12!

Sounds good, I will make the link style look more consistent with the existing UI.

From the screenshot, it looks like you have both `jupyterlab-myst` and `jupyterlab-mystjs` installed. I think that is what is making the styles look a little wonky in the lefthand side (purple border + padding).

**Comment by fperez** [comment]
Ah, good catch, thanks!! I didn't realize that, I'll remove the old one to leave only one of these extensions active.

**Comment by rowanc1** [comment]
Will be merged and fixed up shortly:

![link-style](https://user-images.githubusercontent.com/913249/216148230-fb357a73-3c3a-471d-8d52-cf8affdf98bb.gif)

**Comment by rowanc1** [comment]
This has been released in 0.1.3, links work internally and externally, images were fixed in 0.1.2.

@fperez we also opted to change the behaviour to better deal with jupytext, as of v0.1.3 the default renderer of any markdown cell is MyST. This can be turned off by disabling the extension or uninstalling it. If you have any feedback on that, please let us know!

**Comment by fperez** [comment]
Awesome, thx so much @rowanc1!!

Was just a minute ago discussing this with @tsnow03 for using it in our CryoCloud hub. Your timing couldn't have been better :) 

With the release of JupyterLab 3.6.x I'm also about to do an update of my Stat159 hub for next week, so this is perfect.

Pinging @facusapienza21 too.

**Comment by rowanc1** [comment]
Let me know how I can help out here @tsnow03, the extension is getting quite good! Needs more usage to find all the edge cases. :)

**Comment by tsnow03** [comment]
@rowanc1 I will! It looks super cool. We are excited to try it out soon.
